# Generated by Django 4.1 on 2022-10-15 09:17

from django.db import migrations, models
import misschilds.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to=misschilds.models.upload_to_photo)),
                ('lost_age', models.IntegerField(default=0)),
                ('lost_location', models.CharField(blank=True, max_length=255, null=True)),
                ('lost_date', models.DateField(blank=True, null=True)),
                ('looking', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '실종아동',
                'verbose_name_plural': '실종아동',
            },
        ),
    ]
